Repository powsybl/powsybl-diagram, pull requests merged in 2024-06, with the labels that each got.

#607 Add readthedocs configuration files and first pages
  .gitignore
  docs/.readthedocs.yaml
  docs/Makefile
  docs/README.md
  docs/_static/favicon.ico
  docs/_static/img/nad-example.png
  docs/_static/img/nad-sld-diagrams.jpg
  docs/_static/img/sld-example.svg
  docs/_static/logos/logo_lfe_powsybl.svg
  docs/_static/styles/styles.css
  docs/_templates/page.html
  docs/_templates/sidebar/brand.html
  docs/conf.py
  docs/index.md
  docs/make.bat
  docs/network_area_diagrams/index.md
  docs/network_area_diagrams/layout/layout.md
  docs/requirements.txt
  docs/single_line_diagrams/index.md
  docs/single_line_diagrams/layout/layout.md
Labels: documentation, PR: next-release

#621 Improve test on voltage level detail display
  network-area-diagram/src/test/java/com/powsybl/nad/svg/TextNodeTest.java
  network-area-diagram/src/test/resources/vl_description_substation.svg
Labels: PR: next-release

#619 [NAD] Unknown bus corner cases
  network-area-diagram/src/main/java/com/powsybl/nad/svg/SvgWriter.java
  network-area-diagram/src/test/java/com/powsybl/nad/svg/NominalVoltageStyleTest.java
  network-area-diagram/src/test/resources/IEEE_14_bus_disconnection.svg
Labels: PR: next-release, NAD

#624 Add style for disconnected BusbarSection
  single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/styles/StyleClassConstants.java
  single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/styles/iidm/HighlightLineStateStyleProvider.java
  single-line-diagram/single-line-diagram-core/src/main/resources/highlightLineStates.css
  single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/util/NominalVoltageStyleTest.java
  single-line-diagram/single-line-diagram-core/src/test/resources/InternalBranchesNodeBreaker.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/InternalBranchesNodeBreaker_externalPst.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusBusBreaker.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/NodeDecoratorsBranchStatusNodeBreaker.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/NodeDecoratorsSwitches.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/Test3WTFeederInfoArrowSubstation.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/Test3WTFeederInfoArrowVoltageLevel.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestBatteries.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHFirst.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHLast.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHMiddle.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase11SubstationGraphHNone.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphHH.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphHV.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphMatrix1x2.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphMatrix1x5.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphMatrix2x3.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphVH.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase13ZoneGraphVV.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase1_connectivityLabels.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCase1_equipmentLabels.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseComplexExternCellOnFourSections.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseComplexExternCellOnTwoSections.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseFictitiousBus.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseKeepFictitiousSwitchNode.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseRemoveFictitiousSwitchNode.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestCaseSimpleExternCellOnTwoSections.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestComplexParallelLegsInternalPst.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestFormattingFeederInfos.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestInternCellDifferentSubsections.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestOneLegInternCellDifferentSubsectionsLbs.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestOneLegInternCellDifferentSubsectionsSi.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassSubstation.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestSldClassVl.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestUnknownLibrary.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxBB.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxBT.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxTB.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/TestViewBoxTT.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/consecutive_shunts.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/disconnectedComponentsBusBreaker.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/feederInfoTest.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/noComponentsOnBus.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/nominal_voltage_style_substation.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/nominal_voltage_style_vl2.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/nominal_voltage_style_vl3.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/switchesOnBus.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/topological_style_substation.svg
  single-line-diagram/single-line-diagram-core/src/test/resources/with_frame_background.svg
Labels: PR: next-release
