Repository powsybl/powsybl-diagram, pull requests merged in 2024-01, with the labels that each got.

#577 Fix Javadoc warnings
  single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/GraphRefiner.java
  single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/PositionVoltageLevelLayoutFactoryParameters.java
  single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DirectionalFeederInfo.java
Labels: Javadoc

#575 Nominal voltage filter on whole network
  network-area-diagram/src/main/java/com/powsybl/nad/build/iidm/VoltageLevelFilter.java
  network-area-diagram/src/test/java/com/powsybl/nad/NetworkAreaDiagramTest.java
  network-area-diagram/src/test/resources/IEEE_14_bus_voltage_filter4.svg
  network-area-diagram/src/test/resources/IEEE_14_bus_voltage_filter5.svg
Labels: NAD

#582 Matrix Zone diagram (multiple substations) : documentation update
  single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/layout/zonebygrid/README.md
Labels: PR: waiting-for-review
